= AWS Serverless Computing Lambda
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5


*Applcation Details*

* Create a website monitoring system for their website that will notify them of any issues and make sure to maintain high availability for their customers.

* Social media automation to regularly remind customers about their services and policies.

* Set up custom reminders for their employees and their customers in order to make sure that they know the latest information about the business and, for their customers, new specials that they have running.

* Building a customer service for them to help manage the information about their customers in real time as they get new customers and notify administrators about those changes.

---

So let's take a look at some of these projects in more detail. The first one will be based on simple scheduled events. We'll regularly check the website in order to make sure if it's up or down, and then if it's failing, we'll notify the administrator related to the website. After that, we'll look at how we can integrate third‑party APIs and securely manage API keys, like Twitter's API keys, and integrate that with AWS Lambda. From there, we'll look at how we can use some business logic and Amazon's Simple Email Service, SES, to send email reminders to those employees and those customers. And finally, we'll build a full‑fledged serverless service to help the Globomantics Pet Care company managed their customers, and we'll do this with the Serverless Framework. We'll also talk about what the Serverless Framework is and some other serverless frameworks in later sections. Now, each of our projects in this course will be in Python, but you can also mimic the same functionality in the other supported Lambda runtimes. So let's take a closer look at each of these individual projects and how they'll work. Our first project will call a Lambda canary. We'll be using. AWS' built‑in rate scheduler to trigger our function on a regular basis. We'll set up the project to run every 5 minutes. When the trigger is invoked, our Lambda function will then go review the website and make sure to see its up and functioning and working properly. If something fails in the function, that means that the website was probably down. If something succeeds, that means we're probably good to go. And when the Lambda function succeeds or fails, all of that will be recorded inside CloudWatch Logs. Now, if we see any errors with our Lambda functions, we'll use CloudWatch Alarms to trigger an alert to be notified about the website being out of service. After we finish our Lambda canary project, we'll move on to working on a Twitter bot. This Twitter bot will be on a simpler regular scheduled event, which will happen about every hour. This will allow us to make sure we tweet on a regular basis for Globomantics Pet Care. This will run our code and then also have access to the Twitter API keys that we'll be setting up as part of this project. These API keys will be used in order to tweet to the Twitter API. However, because we don't want to hit Twitter spam limitations, and we don't want to look too spammy in general for our social media, we're going to need to randomize our tweets with Python and then send out those different automated tweets to the API. Now we'll be handling all of this through a few built‑in libraries and tools that I'll be showing you in this project. Now, after we finish that Twitter project, we'll look at workflow automation. Again, we'll be using a scheduled event trigger at particular times of day in order to run some business logic and determine if it is morning right now and we need to remind our employees to get on the road to work or if it's the middle of the day and we need to tell them what work task they actually have assigned to them, maybe like going and emptying out the cats' litter boxes. After that, we'll make sure to remind our customers to come and pick up their pets so that no poor rabbits get left behind. Now, once our workflow automation project has been finished, we'll also be looking at creating a new customer service for Globomantics. It'll start with an API request. Now, this will come in through the AWS API Gateway, and we'll also use the Lambda function behind it to process that incoming request, validate it to make sure it looks appropriate, and then send it over into DynamoDB, a backing database service that we'll be using. Now, we'll integrate a bunch of bundled libraries in with our Lambda function package to help make all of this a lot easier. And whenever we get a new customer in this customer service, it'll send an email to it administrator to notify them that a new customer has been added. Now we could integrate this HTTP API anywhere, and we could use it in front‑end applications or other back‑end services. One important thing to note about this project is that we'll be managing it all with something called the Serverless Framework and helping us build all of these infrastructure components pretty easily in some configuration. So definitely check out this project as it's one of the new ones I've added to this course more recently. So that brings us to the end of our first module. Let's take a look at what we've covered. So far, you've learned about the computing context around serverless functions and the benefits that they offer over traditional architectures, as well as the difficulties you might face while grappling with them. You're also of a bit more of an informed consumer when it comes to serverless function providers and can make informed decisions to know what to look for in those providers. You also understand what's going on in the current landscape with serverless functions and when or when not to use serverless. You also now understand what we'll be building throughout this course, so I hope you're excited to dive right in. In the next module, we'll be getting situated with all of the AWS prerequisites we need in order to create our own Lambda functions, so let's get to it.

